# 中兴测试环境
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.30.104:1521/ORCLCDB
    username: C##EAM_ZTE
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 30
      minimum-idle: 10

  redis:
    cluster:
      nodes: 192.168.30.108:7001, 192.168.30.109:7003, 192.168.30.110:7005, 192.168.30.108:7002, 192.168.30.109:7004, 192.168.30.110:7006
    jedis:
      pool:
        max-active: 50
        min-idle: 0
        max-idle: 50
        max-wait: -1
    key-prefix: dev-

excluded:
  swagger-pages: /eam/csrf,/eam/,/eam/v2/api-docs
  pages: /eam/iam/user/getToken, /eam/,/eam/cas,/eam/index,/eam/login,/eam/logout

sso:
  url: http://mbtt.wzmtr.com:4443/cas
  home: http://192.168.30.153:8002/eam/

cas:
  serverUrlPrefix: "${sso.url}"
  serviceUrlPrefix: "http://192.168.30.153:8002/eam"
  casFilterUrlPattern: "/cas"
  loginUrlPattern: "/login"
  logoutUrlPattern: "/logout"
  successUrlPattern: "/index"
  serviceFront: "http://192.168.30.153:8899/index.html"

diboot:
  core:
    init-sql: false
  iam:
    init-sql: false
  #    anon-urls:
  #      - /swagger**/**
  #      - /webjars/**
  #      - /v3/**
  #      - /doc.html
  #    enable-permission-check: true
  #    token-expires-minutes: 60
  component:
    file:
      init-sql: false
    scheduler:
      init-sql: false
    message:
      init-sql: false
#  devtools:
#    codes-version: 1.0
#    codes-copyright: wzmtr
#    codes-author: eam
#    output-path: eam-server/src/main/java/com/wzmtr/eam/
#    output-path-base: eam-server/src/main/java/com/wzmtr/eam/common/
#    output-path-entity: eam-server/src/main/java/com/wzmtr/eam/entity/
#    output-path-vo: eam-server/src/main/java/com/wzmtr/eam/vo/
#    output-path-dto: eam-server/src/main/java/com/wzmtr/eam/dto/
#    output-path-service: eam-server/src/main/java/com/wzmtr/eam/service/
#    output-path-mapper: eam-server/src/main/java/com/wzmtr/eam/mapper/
#    output-path-sql: eam-server/src/main/resources/

mdm:
  person:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonList?wsdl"
  org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllOrgList?wsdl"
  extra-org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllExtraOrgList?wsdl"
  emp-job:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllEmpJobInfoList?wsdl"
  supp:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppList?wsdl"
  supp-contact:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppContactsList?wsdl"
  person-plus:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonPlusList?wsdl"

local:
  base-url: http://192.168.30.58:8002/rights

minio:
  url: http://zxgd.softether.net:9000
  imgPath: http://zxgd.softether.net:9000
  accessKey: minio
  secretKey: minio123

pro:
  name: eam

eip:
  url: "http://esb.wzmtr.com:7003/iplwebservice/ps/CREATEtodoList?wsdl"

bpmn:
  account: "eamadmin"
  password: "eamadmin"
  url: "http://192.168.30.40:9998/fastflow-admin"