# 中兴测试环境
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.30.130:1521/xe
    username: S1_EAM
    password: S1_EAM@123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 30
      minimum-idle: 10

  rabbitmq:
    host: 192.168.30.130
    port: 5672
    username: admin
    password: 123456
    virtual-host: /eam-s1

  redis:
    host: 192.168.30.130
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 50
        min-idle: 0
        max-idle: 50
        max-wait: -1
    key-prefix: eam-dev-s1-

excluded:
  swagger-pages: /eam/csrf,/eam/,/eam/v2/api-docs
  pages: /eam/iam/user/getToken, /eam/,/eam/cas,/eam/index,/eam/login,/eam/logout

sso:
  url: http://192.168.30.140:8084/cas
  home: http://192.168.30.140:18899/eam/

cas:
  serverUrlPrefix: "${sso.url}"
  serviceUrlPrefix: "http://192.168.30.140:18899/eam"
  casFilterUrlPattern: "/cas"
  loginUrlPattern: "/login"
  logoutUrlPattern: "/logout"
  successUrlPattern: "/index"
  serviceFront: "http://192.168.30.140:18899/index.html"

diboot:
  core:
    init-sql: false
  iam:
    init-sql: false
  #    anon-urls:
  #      - /swagger**/**
  #      - /webjars/**
  #      - /v3/**
  #      - /doc.html
  #    enable-permission-check: true
  #    token-expires-minutes: 60
  component:
    file:
      init-sql: false
    scheduler:
      init-sql: false
    message:
      init-sql: false
#  devtools:
#    codes-version: 1.0
#    codes-copyright: wzmtr
#    codes-author: eam
#    output-path: eam-server/src/main/java/com/wzmtr/eam/
#    output-path-base: eam-server/src/main/java/com/wzmtr/eam/common/
#    output-path-entity: eam-server/src/main/java/com/wzmtr/eam/entity/
#    output-path-vo: eam-server/src/main/java/com/wzmtr/eam/vo/
#    output-path-dto: eam-server/src/main/java/com/wzmtr/eam/dto/
#    output-path-service: eam-server/src/main/java/com/wzmtr/eam/service/
#    output-path-mapper: eam-server/src/main/java/com/wzmtr/eam/mapper/
#    output-path-sql: eam-server/src/main/resources/

mdm:
  person:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonList?wsdl"
  org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllOrgList?wsdl"
  extra-org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllExtraOrgList?wsdl"
  emp-job:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllEmpJobInfoList?wsdl"
  supp:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppList?wsdl"
  supp-contact:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppContactsList?wsdl"
  person-plus:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonPlusList?wsdl"

local:
  base-url: http://192.168.30.140:8003/eam
  data-sync: off

minio:
  url: http://192.168.30.130:9000
  imgPath: http://192.168.30.130:9000
  accessKey: miniominio
  secretKey: miniominio

pro:
  name: eam
  bucket-base: eam-s1

eip:
  url: "http://esb.wzmtr.com:7003/iplwebservice/ps/CREATEtodoList?wsdl"

bpmn:
  account: "eamadmin"
  password: "eamadmin"
  url: "http://36.139.239.105:9998/fastflow-admin"