package com.wzmtr.eam.dto.req.fault;

import lombok.Data;

@Data
public class FaultInfoReqDTO {
    private String recId = " ";
    private String companyCode = " ";
    private String companyName = " ";
    private String faultNo = " ";
    private String faultFlag = " ";
    private String objectCode = " ";
    private String objectName = " ";
    private String trainTrunk = " ";
    private String lineCode = " ";
    private String positionCode = " ";
    private String positionName = " ";
    private String majorName = " ";
    private String systemName = " ";
    private String equipTypeName = " ";
    private String discovererPhone = " ";
    private String position2Code = " ";
    private String partCode = " ";
    private String partName = " ";
    private String majorCode = " ";
    private String systemCode = " ";
    private String equipTypeCode = " ";
    private String faultModule = " ";
    private String faultType = " ";
    private String sourceCode = " ";
    private String faultDisplayCode = " ";
    private String faultDisplayDetail = " ";
    private String faultDetail = " ";
    private String discovererId = " ";
    private String discovererName = " ";
    private String discoveryTime = " ";
    private String fillinUserId = " ";
    private String fillinDeptCode = " ";
    private String fillinTime = " ";
    private String respDeptCode = " ";
    private String assistDeptCode = " ";
    private String repairDeptCode = " ";
    private String publishUserId = " ";
    private String publishTime = " ";
    private String faultLevel = " ";
    private String faultStatus = " ";
    private String workFlowInstId = " ";
    private String workFlowInstStatus = " ";
    private String docId = " ";
    private String remark = " ";
    private String recCreator = " ";
    private String recCreateTime = " ";
    private String recRevisor = " ";
    private String recReviseTime = " ";
    private String recDeletor = " ";
    private String recDeleteTime = " ";
    private String deleteFlag = " ";
    private String archiveFlag = " ";
    private String recStatus = " ";
    private String ext1 = " ";
    private String ext2 = " ";
    private String ext3 = " ";
    private String ext4 = " ";
    private String ext5 = " ";
    private String fillinUserName = " ";
    private String traintag = " ";
    private String faultModuleId = " ";
}
